apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-service
  labels:
    estado: "1"
spec:
  selector:
    matchLabels:
      app: db-service
  template:
    metadata:
      labels:
        app: db-service
    spec:
      containers:
      - name: db-service
        image: asanchez22/db-crud:latest
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: dbdatasql
      volumes:
       - name: dbdatasql
         persistentVolumeClaim:
            claimName: pvc-volume