apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-volume
  labels:
    app: appweb
spec:
  storageClassName: dbdata
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi